### PR TITLE
Use texlive extension

### PR DESCRIPTION
**Pull request by jakobjakobson13**

### CODE REVIEW

**Comment by somas95** [comment]
I'm conflicted about this. I don't like the idea of needing an entire distribution of TexLive to be able to export to pdf, and that's why I did a custom extension with the minimum, but maintaining it it's not trivial....

**Review by somas95 — APPROVED** [review]
Didn't know this was possible! I'll test it, but I think this is the way to go. Thanks!

**Comment by jakobjakobson13** [comment]
I'm sorry but I guess you have to revert the changes if I'm reading the logs right. The texlive module had in all three successful builds the size of 3.5 GB, so I don't think my workaround had any effect at all.

**Comment by jakobjakobson13** [comment]
I'm closing this pull request as it never worked as intended.

**Pull request closed without merging**
